name: Build and deploy documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r _setup/requirements.txt
      - run: pip install -r _setup/doc_requirements.txt
      - run: mkdocs gh-deploy --force